on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # - name: List all changed files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done

      - name : Check Changes in Dirs
        run: |
          DIRS=($(git diff --name-only HEAD^))
          echo "${DIRS[*]}"
          echo $EXCLUDE_FILES

          echo "here"
          for file in ${EXCLUDE_FILES[@]}; do
            echo "$file"
            DIRS=("${DIRS[@]/$file}")
          done
          # echo "The real"
          echo "the ok dir"
          echo "${DIRS[*]}"

          # TODO : check if is dir and set conditions in pipelines like aws and s3 in other word tf vars
          # git status
          # for dir in $DIRS
          # do
          #   echo "${'$dir'[@]}"
          # done
        env: 
          EXCLUDE_FILES: ".github/workflows/blank.yml README.md" 
      # # - name: Init
      #   run: |
      #     terraform init

      # - name: Plan
      #   run: |
      #     terraform plan