on: [push]

jobs:
  test:
    uses: diegotony/gh-pipelines/.github/workflows/python-plugin-diagrams.yml@main
#       - uses: actions/checkout@v2
#       - name: Hello world action step
#         id: hello
#         uses: diegotony/diagrams-action@main
#         with:
#           args: python3 diagram.py
#       # Use the output from the `hello` step
#       - name: Get Files
#         run: ls -lh
