on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: diegotony/diagrams-action@main
        with:
          args: python diagram.py
      # Use the output from the `hello` step
      - name: Get Files
        run: ls -lh
