on: [push]

jobs:
  test:
    uses: diegotony/gh-pipelines/.github/workflows/build-node-app.yml@main
    with:
      node_version: 14
    
#       - uses: actions/checkout@v2

#       - name: Hello world action step
#         id: hello
#         uses: diegotony/diagrams-action@main
#         with:
#           args: python3 diagram.py

#       # Use the output from the `hello` step
#       - name: Get Files
#         run: ls -lh
