on: [push]

jobs:
  semantic-release:
    uses: diegotony/gh-pipelines/.github/workflows/main-module-terraform.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

#       - uses: actions/checkout@v2
#       - name: Hello world action step
#         id: hello
#         uses: diegotony/diagrams-action@main
#         with:
#           args: python3 diagram.py
#       # Use the output from the `hello` step
#       - name: Get Files
#         run: ls -lh
